dependencies:
  - smartcontractkit/chainlink-brwonie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brwonie-contracts@1.1.1'

#dotenv: .env
#wallets:  
#  from_key: ${PRIVATE_KEY}
#networks:
#    default: sepolia