- name: Sepolia (Infura)
  chainid: 11155111
  explorer: https://api-sepolia.etherscan.io/api
  host: https://sepolia.infura.io/v3/1d5011de4ef34eec951bc1c2b5298506
  id: sepolia
  multicall2: '0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696'
  provider: infura